apiVersion: v1
kind: Service
metadata:
  name: url-shortener
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      name: auth-port
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: shortener-port
